### ISSUE TITLE
Compiling in Theos

### ISSUE THREAD

**Issue by Framdark** [cbyrne/MitsuhaForever#11]
When ever I compile in Theos I get this any help would be great 

1 error generated.
make[4]: *** [/Users/ethangottlieb/Downloads/MitsuhaForever-master/.theos/obj/arm64/MSHFPrefsListController.m.f9bb5771.o] Error 1
make[3]: *** [/Users/ethangottlieb/Downloads/MitsuhaForever-master/.theos/obj/arm64/MitsuhaForeverPrefs.bundle/MitsuhaForeverPrefs] Error 2
make[2]: *** [internal-bundle-all_] Error 2
make[1]: *** [MitsuhaForeverPrefs.all.bundle.variables] Error 2
make: *** [internal-all] Error 2

**Comment by CurvedT54** [comment]
Try the new update

**Comment by cbyrne** [comment]
https://github.com/cbyrne/MitsuhaForever/wiki/Compiling-Mitsuha-Forever
