### ISSUE TITLE
Trouble installing the new update

### ISSUE THREAD

**Issue by Bios777** [cbyrne/MitsuhaForever#13]
![D6A802C8-2C14-4D46-BDBC-62F66763A12C](https://user-images.githubusercontent.com/6596758/80533370-cc60fb00-899d-11ea-9034-af719fc25453.png)

Every time I’m trying to update the tweak I’m getting the error you can see in the attached picture. I tried reinstalling but there seems to be a problem with the audiosnapchatserver

**Comment by resonantroamer** [comment]
Same thing is happening to me right now

**Comment by xDOLFYx** [comment]
Same
