### ISSUE TITLE
Mitsusha Wont Install iPhone 11 Pro Max iOS 13.3 Please Fix

### ISSUE THREAD

**Issue by miguelr4720** [cbyrne/MitsuhaForever#14]
i keep getting this error on cydia everytime when i try to install it on my iPhone 11 Pro Max can you please fix?? 

![0F3C2C95-8CA4-4D55-A889-8D37EF462D5E](https://user-images.githubusercontent.com/36649261/80534196-d8809480-896c-11ea-8261-8031321eebf2.png)

**Comment by miguelr4720** [comment]
![FF38AFF8-5597-4FA1-98B0-349E989CC775](https://user-images.githubusercontent.com/36649261/80534521-5d6bae00-896d-11ea-881a-d6155e511ecb.png)

**Comment by miguelr4720** [comment]
is not installing idk why is doing this please fix

**Comment by miguelr4720** [comment]
someone please help me with this

**Comment by resonantroamer** [comment]
having the same problem right now too

**Comment by acegoal07** [comment]
Same issue here

**Comment by xDOLFYx** [comment]
same it can't update so i've removed it and can't install it. Conflict with Audiosnapserver

**Comment by miguelr4720** [comment]
has anyone found a work around this problem?

**Comment by z306334796** [comment]
Same Issue.

**Comment by acegoal07** [comment]
I have been able to get it to work

**Comment by resonantroamer** [comment]
> I have been able to get it to work

What did you do to fix the error it gives?

**Comment by acegoal07** [comment]
I had to install mitsuha forever and the libmitsuha form the debs and not through the repo. I didn’t install audiosnapahot as it seems to work without it and I don’t get any errors

**Comment by incretoto** [comment]
- Download all three debs ( I used **cydownload** on my PC)
- Import them into **Filza**
- Tap on **AudioSnapshotServer** deb and extract it, not install
- Open the folder and delete both **postinst** and **postrm**
- Create deb from the folder by long press on it, tap more, then create deb
- Install them in order **AudioSnapshotServer** -> **libmitsuha** -> **Mitsuha Forever**

That's how I got the new updated **Mitsuha Forever** work on my phone. Good luck!

**Comment by CurvedT54** [comment]
> I had to install mitsuha forever and the libmitsuha form the debs and not through the repo. I didn’t install audiosnapahot as it seems to work without it and I don’t get any errors

I tried this on iphone 11 iOS 13.2.3 and no such luck

**Comment by CurvedT54** [comment]
> * Remove them from Cydia first if you haven't
> * Download all three debs ( I used **cydownload** on my PC)
> * Import them into **Filza**
> * Tap on **AudioSnapshotServer** deb and extract it, not install
> * Open the folder and delete both **postinst** and **postrm**
> * Create deb from the folder by long press on it, tap more, then create deb
> * Install them in order **AudioSnapshotServer** -> **libmitsuha** -> **Mitsuha Forever**
> 
> That's how I got the new updated **Mitsuha Forever** work on my phone. Good luck!

I also tried this but again, no such luck. I guess I will just have to wait for another update.

**Comment by resonantroamer** [comment]
> - Remove them from Cydia first if you haven't
> 
> - Download all three debs ( I used **cydownload** on my PC)
> 
> - Import them into **Filza**
> 
> - Tap on **AudioSnapshotServer** deb and extract it, not install
> 
> - Open the folder and delete both **postinst** and **postrm**
> 
> - Create deb from the folder by long press on it, tap more, then create deb
> 
> - Install them in order **AudioSnapshotServer** -> **libmitsuha** -> **Mitsuha Forever**
> 
> 
> 
> That's how I got the new updated **Mitsuha Forever** work on my phone. Good luck!
> 
> 

Is the actual tweak working for you though? I finally got it to install with these instructions (thank you) but it’s not doing anything  in the Music app

**Comment by incretoto** [comment]
> Is the actual tweak working for you though? I finally got it to install with these instructions (thank you) but it’s not doing anything in the Music app

Yeah, it’s been working just fine together with other tweaks I have, both in Music and Lockscreen.

Have you tried restart mediaserver in the tweak preference and close the Music app or respring?

![49363D84-CA7B-4D6C-9E44-F0AADE8C3718](https://user-images.githubusercontent.com/55074214/80643602-5b215680-8a36-11ea-8634-0df4a26b290a.png)
![268C49BA-10A8-4CD3-BDDB-370D1F6D8312](https://user-images.githubusercontent.com/55074214/80643617-61173780-8a36-11ea-87d9-59fd03f8c87a.png)

**Comment by miguelr4720** [comment]
> > * Remove them from Cydia first if you haven't
> > * Download all three debs ( I used **cydownload** on my PC)
> > * Import them into **Filza**
> > * Tap on **AudioSnapshotServer** deb and extract it, not install
> > * Open the folder and delete both **postinst** and **postrm**
> > * Create deb from the folder by long press on it, tap more, then create deb
> > * Install them in order **AudioSnapshotServer** -> **libmitsuha** -> **Mitsuha Forever**
> > 
> > That's how I got the new updated **Mitsuha Forever** work on my phone. Good luck!
> 
> Is the actual tweak working for you though? I finally got it to install with these instructions (thank you) but it’s not doing anything in the Music app

can you provide screenshots

**Comment by incretoto** [comment]
> I also tried this but again, no such luck. I guess I will just have to wait for another update.

Could you get to install all of three packages? Or where did you get stuck?

**Comment by miguelr4720** [comment]
this sounds to hard to fix i rather wait for a new update

**Comment by incretoto** [comment]
Is this kind of screenshot you want to see?

![E2FCAFAE-E240-418F-967C-A1E3751AD42E](https://user-images.githubusercontent.com/55074214/80644676-07177180-8a38-11ea-92f5-2ec488162aee.png)

**Comment by xDOLFYx** [comment]
> this sounds to hard to fix i rather wait for a new update

It was honestly pretty easy fix for me. I've Removed via Filza that me.conorthedev.audiosnapshot file and installed Mitsusha and then put back those files. Kinda Annoying process but worked for me.

**Comment by incretoto** [comment]
> It was honestly pretty easy fix for me. I've Removed via Filza that me.conorthedev.audiosnapshot file and installed Mitsusha and then put back those files. Kinda Annoying process but worked for me.

Interesting. I did the same thing but it didn’t work for me. Cydia kept showing the same error messages even though I already deleted the files from AudioSnapshotServer. So I had to do a little bit more work to fix it. 😅

**Comment by xDOLFYx** [comment]
> > It was honestly pretty easy fix for me. I've Removed via Filza that me.conorthedev.audiosnapshot file and installed Mitsusha and then put back those files. Kinda Annoying process but worked for me.
> 
> Interesting. I did the same thing but it didn’t work for me. Cydia kept showing the same error messages even though I already deleted the files from AudioSnapshotServer. So I had to do a little bit more work to fix it. 😅

yea i forgot to say after i've removed i also did a respring

**Comment by xDOLFYx** [comment]
But now i have another issue what i have no idea how to fix

**Comment by xDOLFYx** [comment]
Cuz am trying to Change the color of the Wave but it won't change for Spotify, Notification and Lockscreen but on Apple Music it works. so i don't fuckin get it

**Comment by incretoto** [comment]
> But now i have another issue what i have no idea how to fix

You might want to try what I did to install this update since I haven’t had any issue at all. 🥳

**Comment by xDOLFYx** [comment]
i've had this issue from the start. so yea

**Comment by incretoto** [comment]
I just tried to set custom color for Lockscreen and Music app and they worked fine as you can see here.
![34140ECF-79DF-4138-827E-00F53EE8D051](https://user-images.githubusercontent.com/55074214/80646441-b81f0b80-8a3a-11ea-8d3b-d0eca4d249b7.png)
![330B11B7-69EC-4551-8AC7-AC6DBEDA954A](https://user-images.githubusercontent.com/55074214/80646445-bb19fc00-8a3a-11ea-9e4b-520aed23075b.png)

**Comment by xDOLFYx** [comment]
yea i have no clue what am doin wrong

**Comment by CurvedT54** [comment]
> > It was honestly pretty easy fix for me. I've Removed via Filza that me.conorthedev.audiosnapshot file and installed Mitsusha and then put back those files. Kinda Annoying process but worked for me.
> 
> Interesting. I did the same thing but it didn’t work for me. Cydia kept showing the same error messages even though I already deleted the files from AudioSnapshotServer. So I had to do a little bit more work to fix it. 😅

I now have it working in Spotify but the visualizer part of it doesn’t work only a black bar at the bottom of my screen

**Comment by CurvedT54** [comment]
> > I also tried this but again, no such luck. I guess I will just have to wait for another update.
> 
> Could you get to install all of three packages? Or where did you get stuck?

Reference my previous comment all three are installed

**Comment by xDOLFYx** [comment]
> > > It was honestly pretty easy fix for me. I've Removed via Filza that me.conorthedev.audiosnapshot file and installed Mitsusha and then put back those files. Kinda Annoying process but worked for me.
> > 
> > 
> > Interesting. I did the same thing but it didn’t work for me. Cydia kept showing the same error messages even though I already deleted the files from AudioSnapshotServer. So I had to do a little bit more work to fix it. 😅
> 
> I now have it working in Spotify but the visualizer part of it doesn’t work only a black bar at the bottom of my screen

Does it work anywhere else cuz it can be a problem with new version of Spotify cuz i know it won't work if you have Spotify version higher the 8.5.46.588

**Comment by xDOLFYx** [comment]
if you need to downgrade spotify you can use appstore++

**Comment by incretoto** [comment]
> Reference my previous comment all three are installed

Alright, I misunderstood. Well, if after restart mediaserver and respring, the tweak still not working, I guess you gotta wait for conorthedev to fix this issue. Sorry I can’t help.

**Comment by NoReload** [comment]
> * Remove them from Cydia first if you haven't
> * Download all three debs ( I used **cydownload** on my PC)
> * Import them into **Filza**
> * Tap on **AudioSnapshotServer** deb and extract it, not install
> * Open the folder and delete both **postinst** and **postrm**
> * Create deb from the folder by long press on it, tap more, then create deb
> * Install them in order **AudioSnapshotServer** -> **libmitsuha** -> **Mitsuha Forever**
> 
> That's how I got the new updated **Mitsuha Forever** work on my phone. Good luck!

Thank you, this worked for me :)

**Comment by CurvedT54** [comment]
So now Mitsuha itself does nothing while statusviz works so I’m ok with it
