### ISSUE TITLE
Cannot install update

### ISSUE THREAD

**Issue by futureryo** [cbyrne/MitsuhaForever#15]
![4ADD71E5-7E50-48E1-AA48-5A5B1F0D6166](https://user-images.githubusercontent.com/42001512/80571959-7b67fb80-89cb-11ea-8f30-e937594c008a.png)

**Comment by xDOLFYx** [comment]
Same here

**Comment by TheProgramableTurtle** [comment]
Further this

**Comment by treebard86** [comment]
I have the same issue on iOS 13.5 beta 3 on my iPhone X
