### ISSUE TITLE
Re-add custom colours

### ISSUE THREAD

**Issue by josepvcliment** [cbyrne/MitsuhaForever#2]
When you select the color you want with the custom color label, when you start playing the first song after the respring the color is applied, but if I advance it changes to dynamic

**Comment by CookieCoder15** [comment]
This is the same for me.

**Comment by xDOLFYx** [comment]
have the same issue sometimes it kicks back into custom but mostly it's on dynamic. fun fact dynamic is always on Spotify and Lock screen background but lock screen Notification and Apple Music it's mostly on Custom for some fuckin reason.

**Comment by cbyrne** [comment]
Will re-add custom colours in the next update
