### ISSUE TITLE
Causing Apple Music app crash on iPhone X iOS 13.5 beta 3

### ISSUE THREAD

**Issue by treebard86** [cbyrne/MitsuhaForever#27]
Crashes when trying to view Apple Music now playing iOS 13.5 beta 3 iPhone X

**Comment by treebard86** [comment]
https://share.icloud.com/photos/0cNRB8tJ1nKmewDiBV3lXpCPQ

**Comment by AAgamesnl** [comment]
Everyone is having this issue

**Comment by treebard86** [comment]
Still happing on official iOS 13.5 non beta

**Comment by cbyrne** [comment]
Fixed in latest update
