### ISSUE TITLE
iPhone 11 iOS 13.2.3 New Update fixed install issues (statusviz doesn’t work now)

### ISSUE THREAD

**Issue by CurvedT54** [cbyrne/MitsuhaForever#28]
![00E66A95-79B0-40E1-AF70-52691EEE8E2C](https://user-images.githubusercontent.com/46913155/81149180-56cbd080-8f43-11ea-8efe-3246deaace31.png)
It probably just needs an update but we’ll see soon enough

**Comment by CurvedT54** [comment]
![621428DF-C255-4C03-8A14-0B5844CC13AC](https://user-images.githubusercontent.com/46913155/81149594-1d479500-8f44-11ea-976e-24dcde83b9ac.png)
Before update

**Comment by cbyrne** [comment]
https://github.com/cbyrne/MitsuhaForever/wiki/Frequently-Asked-Questions#my-visualiser-isnt-moving-help
