### ISSUE TITLE
crashes on setting change and doesn't work

### ISSUE THREAD

**Issue by xDOLFYx** [cbyrne/MitsuhaForever#29]
After the update to 1.1. Nothin seems to be working if i try to change any setting Springboard crash. I've tried removed preference files, cleaning every file from mitsuha that could be corrupted. Then doin a clean install of it. Nothin seems to fix it. Would love a option of downgrading to 1.0 or some help. Thanks. I can provide screenshots of crashlog if necessary

**Comment by cbyrne** [comment]
Fixed in next update
