### ISSUE TITLE
iPhone 6s - iOS 13.3.1 - Mitsuha Forever crash Apple Music

### ISSUE THREAD

**Issue by pingoublk** [cbyrne/MitsuhaForever#30]
Hey, 
The tweak doesn't work on my device, it crash and put me on safe mode while I want to go on Apple Music app. When I turn it off for Apple Music it stop crashing. I have tested LockScreen and it work fine.

If you need more precise information please come to me.

Chris

**Comment by cbyrne** [comment]
Fixed in latest update
