### ISSUE TITLE
Not working freezes and settings does nothing

### ISSUE THREAD

**Issue by efrojas16** [cbyrne/MitsuhaForever#34]
Mitsuha is frozen on the lockscreen notification player does nothing and when i try to move any slider in settings it sends my device (iphone 11 pro max 13.3) in safemode the previous version before it was pulled from the repo worked flawless for me no issues i have the same tweaks and settings so that shouldnt be a conflict with my tweaks

**Comment by xDOLFYx** [comment]
Hey same buddy. Is dead for me. For the time being am using at least Infinity Version alias the old ass that works only for Spotify and Music App but better then nothing

**Comment by cbyrne** [comment]
Fixed in next update
