### ISSUE TITLE
The tweak doesn't work (mitsuha forever)

### ISSUE THREAD

**Issue by omar3620** [cbyrne/MitsuhaForever#35]
The tweak doesn't work for me every time I open my music didn't allowed me to open it and crashing the my music appreciation

Notes:
I tried to reinstall the tweak and didn't work
I'm in iOS 12.4
The issue didn't exasperated in the downgrade

**Comment by AAgamesnl** [comment]
Everyone has this problem

**Comment by cbyrne** [comment]
Fixed in latest update

**Comment by omar3620** [comment]
ok thank you 👍
