### ISSUE TITLE
Mitsuha Forever wont start

### ISSUE THREAD

**Issue by KyloRen9165** [cbyrne/MitsuhaForever#36]
![4F14E4B0-CDF4-4DA6-88E5-5D86DC1EB7A7](https://user-images.githubusercontent.com/65100591/81489623-6ed88280-92aa-11ea-92c3-40785f081d4f.png)

How can I fix this?
I’ve tried respring,reinstalling and everything but it wont work.Please help
Running iOS13 on iPhone SE

**Comment by cbyrne** [comment]
https://github.com/cbyrne/MitsuhaForever/wiki/Frequently-Asked-Questions#my-visualiser-isnt-moving-help
