### ISSUE TITLE
[bug] app Crash when opening music table(see screenshot)

### ISSUE THREAD

**Issue by AAgamesnl** [cbyrne/MitsuhaForever#40]
Hey...

The music app crashes when I open the now playing pannel.. not system crash
![E1814846-58D3-473E-BE9A-0990D98DE7C8](https://user-images.githubusercontent.com/19744374/82728376-211f3980-9cf0-11ea-83ca-8b6ae3f53bce.jpeg)
I don’t have any music tweaks installed.
This happened on the new update 1.1
I tried restoring settings in the settings but that didn’t work

IPhone X  iOS 13.4 Checkra1n

**Comment by cbyrne** [comment]
Fixed in latest update
