### ISSUE TITLE
Doesn’t move

### ISSUE THREAD

**Issue by neoooooooooooooo** [cbyrne/MitsuhaForever#41]
![8E5405D7-66A9-4A93-84E8-BA20AC855501](https://user-images.githubusercontent.com/65871886/82764885-ebd83000-9e44-11ea-8649-da20ce2968fc.png)
![E6E298E4-D61B-445D-9137-7988010EC9D3](https://user-images.githubusercontent.com/65871886/82764888-f1357a80-9e44-11ea-9184-34668dea362f.png)
![09727DA0-5EA6-4115-8502-26A0BCFD7ADE](https://user-images.githubusercontent.com/65871886/82764890-f397d480-9e44-11ea-858c-f3f11856c471.png)
![E3D6E6CB-23A6-422E-A913-CDE153BD6835](https://user-images.githubusercontent.com/65871886/82764891-f4c90180-9e44-11ea-9dc0-e5cf1566d731.png)
![05668664-79D5-4D10-A4E9-D97B5459884A](https://user-images.githubusercontent.com/65871886/82764893-f5619800-9e44-11ea-9b51-f41ebaadfbd6.png)
The visualiser doesn’t move anymore, it was working for a few mins after downloading. I’ve tried uninstalling, respringing, deleting and installing Spotify, deleting a tweak that might be interrupting and did the same thing all over again but it’s still not doing anything.

**Comment by neoooooooooooooo** [comment]
Other than changing colour*

**Comment by burritosoftware** [comment]
may I ask what that miniplayer is?

**Comment by ZhongDev** [comment]
> may I ask what that miniplayer is?
Sylph (very probably)

**Comment by cbyrne** [comment]
https://github.com/cbyrne/MitsuhaForever/wiki/Frequently-Asked-Questions#my-visualiser-isnt-moving-help
