### ISSUE TITLE
not working. black box.

### ISSUE THREAD

**Issue by PXOLneo** [cbyrne/MitsuhaForever#42]
When i unlock my phone there is a black box at the bottom and my spring board keeps crashing when i try to change a setting (without even pressing “apply”) i deleted time audiosnapshotserver to see if that would do anything and it removed the black box and also nothing happens when i play music (with audiosnapshotserver still installed) it just has the black box. i’m on ios version 13.3.1 and i have an iphone 7.
![63AF13F1-E9E4-4EBD-8C2A-5A75CE04C655](https://user-images.githubusercontent.com/65886778/82784489-a01a8c00-9e2e-11ea-8869-070aa492dd1d.png)

**Comment by PXOLneo** [comment]
i’m on ios version 13.3.1 and on an iphone 7

**Comment by PXOLneo** [comment]
ok update: i enabled “hide visualizer” or whatever it’s called and it got rid of the black box but it still doesn’t show anything when i play music, no visualizer

**Comment by cbyrne** [comment]
Check [this out](https://github.com/cbyrne/MitsuhaForever/wiki/Frequently-Asked-Questions#my-visualiser-isnt-moving-help)
