### ISSUE TITLE
Mitsuha Forever barely does anything

### ISSUE THREAD

**Issue by unskilledmagician** [cbyrne/MitsuhaForever#5]
I installed this and it added the visualizer thing. I put on some heavy stuff to test it and it just sat there and wobbled a little with basically no change no matter how I edited the settings. I'm using it on spotify if that matters.

**Comment by cbyrne** [comment]
https://github.com/cbyrne/MitsuhaForever/wiki/Frequently-Asked-Questions#my-visualiser-isnt-moving-help
