### ISSUE TITLE
Mitsuha forever not working on iPad 

### ISSUE THREAD

**Issue by Awesomecookieland** [cbyrne/MitsuhaForever#8]
Please help I installed it fine but when I try to make it work it just wouldn’t

**Comment by th3sn3k** [comment]
Doesn’t work and causes a crash of Apple music

**Comment by MyCatCondo** [comment]
For me it crashes my iPad when I mess with anything in its settings. It reboots me to safe mode. It's extremely annoying.

**Comment by cbyrne** [comment]
Fixed in latest update
