### ISSUE TITLE
spotify broken

### ISSUE THREAD

**Issue by YegFire** [cbyrne/MitsuhaForever#9]
when u open the playing screen for spotify the visualizer overlays the controls so you can’t pause or skip the songs.

**Comment by CrimsonCR0W** [comment]
same here, it worked on older version of spotify and it doesnt since ive updated

**Comment by CrimsonCR0W** [comment]
u can get appstore ++ from cydia and hold open off spotify on appstore , press downgrade and find a version that still works with the visualiser

**Comment by CrimsonCR0W** [comment]
just tested it on 8.5.22 and it works, it can probably run on a few never ones but im too lazy to check xD, so that should be ur fix

**Comment by alacielx** [comment]
Spotify 8.5.46 is the latest version that it works on. It breaks on 8.6.47
